apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-udp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
  - name: unfi-stun
    port: 3478
    protocol: UDP
    targetPort: 3478
  - name: ap-discovery
    port: 10001
    protocol: UDP
    targetPort: 10001
  - name: syslog
    port: 5514
    protocol: UDP
    targetPort: 5514
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
