---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activityrelay.fullname" . }}-config
  labels:
    {{- include "activityrelay.labels" . | nindent 4 }}
data:
  ACTOR_PEM: "/var/lib/relay/actor.pem"
  {{- if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ template "activityrelay.redis.fullname" . }}-master:6379"
  {{- else }}
  REDIS_URL: "redis://{{ .Values.redis.externalRedis.host }}:{{ .Values.redis.externalRedis.port }}"
  {{- end}}
  RELAY_BIND: "0.0.0.0:{{ .Values.activityrelay.server.port }}"
  RELAY_DOMAIN: "{{ .Values.activityrelay.config.relay_domain }}"
  RELAY_SERVICENAME: "{{ .Values.activityrelay.config.relay_servicename }}"
  JOB_CONCURRENCY: "{{ .Values.activityrelay.config.job_concurrency }}"
