{{- if not .Values.activityrelay.actor.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activityrelay.fullname" . }}-actor-key
  labels:
    {{- include "activityrelay.labels" . | nindent 4 }}
data:
  actor.pem: {{ genPrivateKey "rsa" | b64enc }}
{{- end }}
