---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "activityrelay.fullname" . }}-server
  labels:
    {{- include "activityrelay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.activityrelay.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "activityrelay.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server