---
argo-cd:
  global:
    image:
      tag: v2.2.5

  controller:
    enableStatefulSet: true

  redis:
    image:
      repository: redis
      tag: 6.2.6-alpine

  redis-ha:
    enabled: true
    image:
      repository: redis
      tag: 6.2.6-alpine

  dex:
    enabled: false

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 85
      targetMemoryUtilizationPercentage: 85

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - argocd-repo-server
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - argocd
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - repo-server
            topologyKey: "kubernetes.io/hostname"

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 1
        memory: 512Mi

  configs:
    secret:
      extra:
        oidc.keycloak.clientSecret: 3c9eac31-8222-476f-b367-01641b491650

  server:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 6
      targetCPUUtilizationPercentage: 85
      targetMemoryUtilizationPercentage: 85

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - argocd-server
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - argocd
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - server
            topologyKey: "kubernetes.io/hostname"

    resources:
      limits:
        cpu: 1
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    config:
      url: https://argo.lab.intahnet.co.uk/
      oidc.config: |
        name: Keycloak
        issuer: https://sso.intahnet.co.uk/auth/realms/intahnet.co.uk
        clientID: argocd-lab
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes:
          - openid
          - profile
          - email
          - groups

    rbacConfig:
      policy.csv: |
        g, admins, role:admin
