---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflared.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    tunnel: {{ required "A valid .Values.tunnelID entry required!" .Values.tunnelID }}
    credentials-file: /etc/cloudflared/{{ required "A valid .Values.tunnelID entry required!" .Values.tunnelID }}.json
    metrics: 0.0.0.0:2000
    ingress: {{ toYaml .Values.ingress | nindent 6 }}
