---
# yamllint disable-line
{{- if eq .Values.kind "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cloudflared.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
{{- if .Values.strategy }}
  updateStrategy:
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudflared.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cloudflared.name" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2000"
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
            - tunnel
            - --no-autoupdate
            - --config
            - /etc/cloudflared/config.yaml
            - run
          ports:
            - name: prometheus
              containerPort: 2000
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tunnel-secret-volume
          secret:
            secretName: {{ include "cloudflared.name" . }}-tunnel-secret
            defaultMode: 420
            optional: false
        - name: cloudflared-config-volume
          configMap:
            name: {{ include "cloudflared.name" . }}-config
            defaultMode: 420
            optional: false
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.topologySpreadConstraints | indent 8 }}
{{- end }}
{{- end }}
